
query GetLists {
  lists {
    nodes {
      author {
        node {
          username
          avatar {
            url
          }
        }
      }
      date
      id
      lists {
        description
        ispublic
        name
        type
        image {
          node {
            sourceUrl
          }
        }
      }
    }
  }
}
