// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/search/atoms/BaseButton.vue')['default']
    BaseCard: typeof import('./components/search/atoms/BaseCard.vue')['default']
    BaseCheckbox: typeof import('./components/search/atoms/BaseCheckbox.vue')['default']
    BaseLogo: typeof import('./components/search/atoms/BaseLogo.vue')['default']
    BaseSelect: typeof import('./components/search/molecules/BaseSelect.vue')['default']
    BaseText: typeof import('./components/search/atoms/BaseText.vue')['default']
    BaseTitle: typeof import('./components/search/atoms/BaseTitle.vue')['default']
    GithubIcon: typeof import('./components/search/atoms/GithubIcon.vue')['default']
    HalfSolidStarIcon: typeof import('./components/search/atoms/HalfSolidStarIcon.vue')['default']
    MeiliSearchBar: typeof import('./components/search/organisms/MeiliSearchBar.vue')['default']
    MeiliSearchFacetFilter: typeof import('./components/search/organisms/MeiliSearchFacetFilter.vue')['default']
    MeiliSearchPagination: typeof import('./components/search/organisms/MeiliSearchPagination.vue')['default']
    MeiliSearchProvider: typeof import('./components/search/organisms/MeiliSearchProvider.vue')['default']
    MeiliSearchRangeFilter: typeof import('./components/search/organisms/MeiliSearchRangeFilter.vue')['default']
    MeiliSearchRatingFilter: typeof import('./components/search/organisms/MeiliSearchRatingFilter.vue')['default']
    MeiliSearchResults: typeof import('./components/search/organisms/MeiliSearchResults.vue')['default']
    MeiliSearchSorting: typeof import('./components/search/organisms/MeiliSearchSorting.vue')['default']
    MeiliSearchStats: typeof import('./components/search/organisms/MeiliSearchStats.vue')['default']
    PageNumber: typeof import('./components/search/molecules/PageNumber.vue')['default']
    ProductCard: typeof import('./components/search/organisms/ProductCard.vue')['default']
    RangeSlider: typeof import('./components/search/molecules/RangeSlider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/search/molecules/SearchInput.vue')['default']
    SelectArrow: typeof import('./components/search/atoms/SelectArrow.vue')['default']
    SocialLink: typeof import('./components/search/molecules/SocialLink.vue')['default']
    SolidStarIcon: typeof import('./components/search/atoms/SolidStarIcon.vue')['default']
    StarIcon: typeof import('./components/search/atoms/StarIcon.vue')['default']
    StarRating: typeof import('./components/search/molecules/StarRating.vue')['default']
    TheNavbar: typeof import('./components/search/organisms/TheNavbar.vue')['default']
    TwitterIcon: typeof import('./components/search/atoms/TwitterIcon.vue')['default']
    XIcon: typeof import('./components/search/atoms/XIcon.vue')['default']
  }
}