

query GetActivities {
  members {
    nodes {
      activities(where: {order: DESC, type: ACTIVITY_UPDATE, component: ACTIVITY}) {
        nodes {
          content
          id
          date
          status
          title
          type
        }
      }
    }
  }
}


  mutation CREATE_ACTIVITY($content: String!) {
    createActivity(input: {content: $content, type: ACTIVITY_UPDATE}) {
    activity {
      content
      date
      status
      title
      type
    }
  }
}

  mutation UPDATE_ACTIVITY($content: String!, $id: ID!) {
    updateActivity(input: {content: $content, type: ACTIVITY_UPDATE, id: $id}) {
      activity {
        content
        date
        id
        status
        title
        type
      }
    }
  }

  mutation DELETE_ACTIVITY($id: ID!) {
    deleteActivity(input: {id: $id}) {
      activity {
        id
      }
    }
  }

