

query GetBlogBar {
  categories {
    nodes {
      parent {
        node {
          id
          name
        }
      }
    }
  }
  nodeByUri(uri: "blog") {
    ... on Page {
      id
      title
      content
    }
  }
}
