

query GetMembers {
  members {
    nodes {
      avatar {
        url
      }
      description
      id
      memberTypes
      url
      username
      totalFriendCount
      locale
      latestUpdate
    }
  }
}

